theme:
  #name: material
  name: readthedocs

site_name: Doctlin

plugins:
  - search
  - i18n:
      default_language: ja
#      languages:
#        en: English
#        ja: 日本語
      languages:
        default:
          name: Default (ja)
          build: true
        en:
          name: English
          build: true
          site_name: "Doctlin document"
        ja:
          name: 日本語
          build: true
          site_name: "Docutlin document JP"
      nav_translations:
        en:
          About: About
          Reference: Code Reference
          Test: Test
  - mkdocstrings:
      watch:
        - doctlin
#    custom_templates: templates
#    default_handler: python
#    handlers:
#      python:
#        options:
#          show_source: true
#nav:
#  - index.en.md
#  - index.md
#  - About:
#    - en/about.en.md
#    - ja/about.en.md
#  - Test:
#      - en/test.en.md
#      - ja/test.en.md
#  - Code Reference:
#      - reference/
#      - reference/