site_name: Doctlin Document
nav:
  - Home: index.md
  - テスト: test.md
  - Code Reference:
      - Doctlin: doctlin-reference.md
#theme: readthedocs
markdown_extensions:
  - pymdownx.arithmatex
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
plugins:
  - search
  - mkdocstrings

theme:
  name: material
  language: 'ja'
extra:
  search:
    language: 'ja'
  generator: false
